spring.application.name=contest
server.port=8085
spring.datasource.url=jdbc:mysql://localhost:3306/contest
spring.datasource.username=root
spring.datasource.password=omkar@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# JWT Config
app.jwt.secret=I love to write code but i love more to read book lets reads book and keep this country safe from bjp
app.jwt.expiration=604800000
app.jwt.temp-expiration=300000

# Cookie Config
app.cookie.name=devconnect.sid
app.cookie.max-age=604800
app.cookie.secure=false

# Cloudinary Config
cloudinary.cloud-name=dlxlghtfz
cloudinary.api-key=989463367741133
cloudinary.api-secret=r4iqU7o3DFeuUX5n7b1vabBw-Yo

# Redis Config
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379

# RabbitMQ Config
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest